[versions]
kotlin = "1.8.0"
kotlinx-coroutines = "1.7.3"
kodein = "7.18.0"
springframework = "3.1.0"
exposed = "0.41.1"
paging = "3.2.1"

[libraries]
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed"}
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed"}
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed"}
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging"}
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging"}

[bundles]
[plugins]